### ISSUE TITLE
segments: filter by tags/mapIDs doesn't work

### ISSUE THREAD

**Issue by stephan83** [stratumn/agent-ui#18]
It calls the old agent-js URL:

`http://localhost:3000/shipment/segments?process=shipment&limit=20&mapId=a+b&prevLinkHash=&tags=sdasd`

Instead of:

`http://localhost:3000/shipment/segments?process=shipment&limit=20&mapIds[]=a&mapIds[]=b&prevLinkHash=&tags[]=sdasd`

I think it's because agent-client-js needs to be updated.

**Comment by such** [comment]
resolved by stratumn/agent-ui#20
